export const PARTNER_SUBSCRIPTION_PLANS = {
  starter: {
    value: "starter",
    label: "Starter",
    price: "$0/yr",
    monthlyPrice: 0,
    monthlyPriceCents: 0,
    maxProviders: 2,
    description: "Simple yearly entry plan.",
    features: ["Up to 2 businesses"],
    squarePlanVariationEnvVar: "SQUARE_PLAN_VARIATION_STARTER_ANNUAL_ID",
  },
  spotlight: {
    value: "spotlight",
    label: "Spotlight",
    price: "$1,000/yr",
    monthlyPrice: 1000,
    monthlyPriceCents: 100000,
    maxProviders: 5,
    description: "Built for growing teams.",
    features: ["3-5 businesses"],
    squarePlanVariationEnvVar: "SQUARE_PLAN_VARIATION_SPOTLIGHT_ANNUAL_ID",
  },
  standard: {
    value: "standard",
    label: "Standard",
    price: "$1,875/yr",
    monthlyPrice: 1875,
    monthlyPriceCents: 187500,
    maxProviders: 15,
    description: "Built for scaling teams.",
    features: ["6-15 businesses"],
    squarePlanVariationEnvVar: "SQUARE_PLAN_VARIATION_STANDARD_ANNUAL_ID",
  },
  premium: {
    value: "premium",
    label: "Premium",
    price: "$3,000/yr",
    monthlyPrice: 3000,
    monthlyPriceCents: 300000,
    maxProviders: 30,
    description: "Built for larger teams.",
    features: ["16-30 businesses"],
    squarePlanVariationEnvVar: "SQUARE_PLAN_VARIATION_PREMIUM_ANNUAL_ID",
  },
  enterprise: {
    value: "enterprise",
    label: "Enterprise",
    price: "$5,000/yr",
    monthlyPrice: 5000,
    monthlyPriceCents: 500000,
    maxProviders: 100,
    description: "Built for enterprise organizations.",
    features: ["31-100 businesses"],
    squarePlanVariationEnvVar: "SQUARE_PLAN_VARIATION_ENTERPRISE_ANNUAL_ID",
  },
} as const;

export type PartnerSubscriptionPlan = keyof typeof PARTNER_SUBSCRIPTION_PLANS;

export const PARTNER_SUBSCRIPTION_PLAN_LIST = Object.values(PARTNER_SUBSCRIPTION_PLANS);
